version: "3"

services:
  bytebase:
    image: bytebase/bytebase:2.3.0
    restart: always
    command:
      - '--data'
      - '/var/opt/bytebase'
      - '--external-url'
      - 'http://127.0.0.1:8080'
    environment:
      TZ: Asia/Shanghai
    networks:
      - bytebase-net
    volumes:
      - /bytebase/data:/var/opt/bytebase

  nginx:
    image: nginx
    restart: always
    depends_on:
      - bytebase
    environment:
      TZ: Asia/Shanghai
    networks:
      - bytebase-net
    ports:
      - 9080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/tls.crt:/etc/ssl/certs/tls.crt
      - ./nginx/ssl/tls.key:/etc/ssl/private/tls.key

networks:
  bytebase-net:
