version: '3.6'

services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    privileged: true
    hostname: gitlab
    environment:
      GITLAB_ROOT_PASSWORD: dyz@0808
    networks:
      - gitlab
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
      - '5005:5005'
    volumes:
      - /data/gitlab/config:/etc/gitlab
      - /data/gitlab/logs:/var/log/gitlab
      - /data/gitlab/data:/var/opt/gitlab
      - .:/workspace
    shm_size: '256m'

  gitlab-runner:
    depends_on:
      - gitlab
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    hostname: gitlab-runner
    privileged: true
    networks:
      - gitlab
    ports:
      - 9252:9252
    volumes:
      - /data/gitlab-runner/etc:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  gitlab:
