version: '3'

services:
  jira:
    build:
      context: .
    container_name: jira
    hostname: jira
    ports:
      - 8081:8080
    networks:
      - jira
    volumes:
      - /var/atlassian/application-data/jira
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: jira
    ports:
      - 5432:5432
    networks:
      - jira
    volumes:
      - /var/lib/postgresql/data

  ## jira setup: database not empty error, no solutions...
  # mysql:
  #   image: mysql
  #   container_name: mysql
  #   hostname: mysql
  #   environment:
  #     MYSQL_DATABASE: jira
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - 3307:3306
  #   networks:
  #     - jira
  #   volumes:
  #     - /var/lib/mysql

networks:
  jira:
