version: '3'

services:
  master:
    container_name: keepalived_master
    build:
      context: .
      args:
        STATE: MASTER
        PRIORITY: 100
        VIP: 192.168.200.140
    privileged: true
    networks:
      keepalived_net:
        ipv4_address: 192.168.200.132
  backup:
    container_name: keepalived_backup
    build:
      context: .
      args:
        STATE: BACKUP
        PRIORITY: 90
        VIP: 192.168.200.140
    privileged: true
    networks:
      keepalived_net:
        ipv4_address: 192.168.200.133

networks:
  keepalived_net:
    driver: bridge
    driver_opts:
      parent: wlan0
    ipam:
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.2
